# Build step 1(installing node modules and preparing compiled build)
# FROM node:12.20.1-alpine as build
# WORKDIR /app
# ENV PATH /app/node_modules/.bin:$PATH
# COPY package.json ./
# RUN npm i --silent
# RUN npm install 
# COPY . ./
# # ENV REACT_APP_HOST_IP_ADDRESS $API_URL
# RUN npm run build

# # Build step 2(Deploying build on NGINX)
# FROM nginx:1.13
# RUN  apt-get update \
#   && apt-get install -y wget \
#   && rm -rf /var/lib/apt/lists/*
# RUN rm -rf /usr/share/nginx/html/*
# COPY --from=build /app/nginx/nginx.conf /etc/nginx/conf.d/default.conf:ro
# COPY --from=build /app/dist /usr/share/nginx/html
FROM node:18-slim
ARG AXIOS_BASEURL
ARG AXIOS_BROWSER_BASEURL
RUN apt-get update
RUN apt-get update || : && apt-get install python3 make g++ -y
WORKDIR /usr/src/app
COPY package.json ./
COPY yarn.lock ./
RUN yarn install
COPY . .
RUN yarn build
ENV HOST=0.0.0.0
