FROM --platform=linux/amd64 node:18-slim
ARG AXIOS_BASEURL
ARG AXIOS_BROWSER_BASEURL
RUN apt-get update
RUN apt-get update || : && apt-get install python3 make g++ -y
WORKDIR /usr/src/app
COPY package.json ./
COPY yarn.lock ./
RUN yarn install
COPY . .
RUN yarn build
ENV HOST=0.0.0.0
