# Generated by Django 4.2.5 on 2023-10-03 22:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
                ('public', models.BooleanField()),
                ('host', models.CharField(max_length=255)),
                ('displayName', models.CharField(max_length=255)),
                ('url', models.TextField()),
                ('github', models.TextField()),
                ('profileImage', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ConnectedNode',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=255)),
                ('host', models.CharField(max_length=255)),
                ('teamName', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('type', models.CharField(max_length=255)),
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('source', models.CharField(max_length=255)),
                ('origin', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('contentType', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('published', models.DateTimeField()),
                ('categories', models.TextField()),
                ('count', models.IntegerField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialDistribution.author')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('type', models.CharField(max_length=255)),
                ('published', models.DateTimeField()),
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialDistribution.author')),
                ('posts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialDistribution.post')),
            ],
        ),
        migrations.CreateModel(
            name='FriendRequest',
            fields=[
                ('status', models.CharField(max_length=255)),
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('from_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_author', to='socialDistribution.author')),
                ('to_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_author', to='socialDistribution.author')),
            ],
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('status', models.CharField(max_length=255)),
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('from_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_author_follow', to='socialDistribution.author')),
                ('to_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_author_follow', to='socialDistribution.author')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('type', models.CharField(max_length=255)),
                ('comment', models.TextField()),
                ('contentType', models.CharField(max_length=255)),
                ('published', models.DateTimeField()),
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('commenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialDistribution.author')),
                ('parentPost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialDistribution.post')),
            ],
        ),
        migrations.AddField(
            model_name='author',
            name='comments',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialDistribution.comment'),
        ),
        migrations.AddField(
            model_name='author',
            name='followers',
            field=models.ManyToManyField(through='socialDistribution.Follow', to='socialDistribution.author'),
        ),
        migrations.AddField(
            model_name='author',
            name='posts',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialDistribution.post'),
        ),
        migrations.AddField(
            model_name='author',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
