# Generated by Django 4.2.4 on 2023-10-27 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialDistribution', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='type',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='type',
        ),
        migrations.RemoveField(
            model_name='like',
            name='type',
        ),
        migrations.RemoveField(
            model_name='post',
            name='type',
        ),
    ]
