# Generated by Django 4.2.4 on 2023-10-28 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialDistribution', '0002_remove_author_type_remove_comment_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='url',
        ),
    ]
