# Generated by Django 4.2.4 on 2023-10-28 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialDistribution', '0003_remove_author_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='author',
            name='followers',
        ),
        migrations.RemoveField(
            model_name='author',
            name='posts',
        ),
    ]
