# Generated by Django 4.2.4 on 2023-10-29 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialDistribution', '0005_remove_author_public_post_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='unlisted',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
