# Generated by Django 4.2.4 on 2023-10-29 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialDistribution', '0008_post_image_post_image_link_post_shared_with_friends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='profileImage',
            field=models.ImageField(blank=True, null=True, upload_to='post_images/'),
        ),
    ]
