# Generated by Django 4.2.4 on 2023-10-30 07:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('socialDistribution', '0011_alter_author_options_alter_author_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
