# Generated by Django 4.2.4 on 2023-10-30 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialDistribution', '0012_alter_author_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='imageOnlyPost',
            field=models.BooleanField(default=False),
        ),
    ]
