# Generated by Django 4.2.4 on 2023-11-19 08:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialDistribution', '0002_alter_author_displayname_alter_author_github_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='published',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='commentlike',
            name='published',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='postlike',
            name='published',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
