# Generated by Django 4.2.4 on 2023-11-19 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialDistribution', '0003_alter_comment_published_alter_commentlike_published_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='status',
        ),
        migrations.RemoveField(
            model_name='friendrequest',
            name='status',
        ),
    ]
