# Generated by Django 4.2.6 on 2023-11-19 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialDistribution', '0002_userprofile'),
        ('socialDistribution', '0004_remove_follow_status_remove_friendrequest_status'),
    ]

    operations = [
    ]
