# Generated by Django 4.2.6 on 2023-11-20 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialDistribution', '0005_merge_20231119_1638'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
