# Generated by Django 4.2.4 on 2023-11-21 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialDistribution', '0007_rename_commenter_comment_author_friendrequest_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inbox',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='FriendRequest',
        ),
    ]
