# Generated by Django 4.2.4 on 2023-11-21 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialDistribution', '0008_alter_inbox_content_delete_friendrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connectednode',
            name='host',
        ),
    ]
