# Generated by Django 4.2.4 on 2023-11-21 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialDistribution', '0009_remove_connectednode_host'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inbox',
            name='friend_request_status',
        ),
    ]
