# Generated by Django 4.2.4 on 2023-11-21 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialDistribution', '0010_remove_inbox_friend_request_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='type',
            field=models.CharField(default='author', max_length=255),
        ),
        migrations.AddField(
            model_name='comment',
            name='type',
            field=models.CharField(default='comment', max_length=255),
        ),
        migrations.AddField(
            model_name='commentlike',
            name='type',
            field=models.CharField(default='like', max_length=255),
        ),
        migrations.AddField(
            model_name='follow',
            name='type',
            field=models.CharField(default='follow', max_length=255),
        ),
        migrations.AddField(
            model_name='post',
            name='type',
            field=models.CharField(default='post', max_length=255),
        ),
        migrations.AddField(
            model_name='postlike',
            name='type',
            field=models.CharField(default='like', max_length=255),
        ),
    ]
