# Generated by Django 4.2.4 on 2023-11-21 21:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialDistribution', '0011_author_type_comment_type_commentlike_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inbox',
            name='recipient',
        ),
        migrations.RemoveField(
            model_name='inbox',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='inbox',
            name='type',
        ),
        migrations.AddField(
            model_name='inbox',
            name='author',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, related_name='inbox_owner', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
