# Generated by Django 4.2.4 on 2023-11-21 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialDistribution', '0012_remove_inbox_recipient_remove_inbox_sender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inbox',
            name='content',
        ),
        migrations.AddField(
            model_name='inbox',
            name='items',
            field=models.TextField(blank=True, default='[]', null=True),
        ),
    ]
