# Generated by Django 4.2.4 on 2023-11-22 06:48

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialDistribution', '0013_remove_inbox_content_inbox_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='from_author',
        ),
        migrations.RemoveField(
            model_name='follow',
            name='to_author',
        ),
        migrations.AddField(
            model_name='follow',
            name='follower',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='follow',
            name='following',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, related_name='followers', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='follow',
            name='published',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='follow',
            name='status',
            field=models.CharField(default='Pending', max_length=255),
        ),
        migrations.AlterField(
            model_name='inbox',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbox', to=settings.AUTH_USER_MODEL),
        ),
    ]
