# Generated by Django 4.2.4 on 2023-11-23 02:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialDistribution', '0014_remove_follow_from_author_remove_follow_to_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectednode',
            name='api_user',
            field=models.ForeignKey(default='e26e723712e544198cb3c1ec1890b096', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
