# Generated by Django 4.2.4 on 2023-11-25 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialDistribution', '0017_alter_comment_author_alter_comment_parentpost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentlike',
            name='context',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commentlike',
            name='object',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commentlike',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postlike',
            name='context',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postlike',
            name='object',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postlike',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='displayName',
            field=models.CharField(blank=True, default='User', max_length=255, null=True),
        ),
    ]

