# Generated by Django 4.2.4 on 2023-11-28 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialDistribution', '0022_auto_20231125_0735'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='image',
            new_name='profileImage',
        ),
    ]
