# Generated by Django 4.2.4 on 2023-11-27 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialDistribution', '0025_alter_commentlike_comment_alter_postlike_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='summary',
            field=models.TextField(blank=True, default='Follow Request', null=True),
        ),
    ]
